version: "3.3"
services:      
  tika:
    image: apache/tika
    ports:
      - "9998:9998"
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      TIKA_CLIENT_ONLY: 1
      TIKA_SERVER_ENDPOINT: http://tika:9998
    depends_on:
      - tika    
